---

# Run with:
# ansible-playbook cluster.yml -i hosts

- name: kubernetes
  hosts: all
  become: true
  gather_facts: false
  roles:
    - kubernetes
  
- name: control plane
  hosts: master
  become: true
  gather_facts: false
  roles:
    - control-plane

- name: workers
  hosts: worker
  become: true
  gather_facts: false
  tasks:
    - name: reset
      shell: kubeadm reset
      
    - name: join cluster
      shell: "{{hostvars['token-holder']['joincmd']}}"
