---

- name: Change Hostname
  copy:
    content: "{{ hostname }}"
    dest: /etc/hostname

- name: local hostname discovery
  lineinfile:
    path: /etc/hosts
    line: 127.0.0.1 {{hostname}}

- name: add docker repo key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker repo
  apt_repository:
    repo: deb [arch=armhf] https://download.docker.com/linux/raspbian stretch edge
    filename: docker
    state: present

- name: install docker
  apt:
    name: docker-ce
    update_cache: yes
    state: present

- user: 
    name: pi
    groups: docker
    append: yes        

- name: Disable swap
  shell: |
    dphys-swapfile swapoff
    dphys-swapfile uninstall
    update-rc.d dphys-swapfile remove

- name: Set cgroups config
  shell: |
    CGROUPCONFIG='cgroup_enable=cpuset cgroup_memory=1'
    if ! grep -q "$CGROUPCONFIG" /boot/cmdline.txt; then
      BOOTFILE=`cat /boot/cmdline.txt`
      echo ${BOOTFILE} $CGROUPCONFIG > /boot/cmdline.txt
    fi

- name: Reboot
  shell: sleep 2 && /sbin/shutdown -r now
  async: 1
  poll: 0

- name: waiting for boot
  wait_for_connection:
    delay: 5

- name: add kubernetes repo key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: add kubernetes repo
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes

- name: install kubernetes
  apt:
    update_cache: yes
    name: kubeadm 
    state: present
